### ISSUE TITLE
Auth0::BadRequest: {"statusCode":400,"error":"Bad Request","message":"The connection does not exist.","errorCode":"i...

### ISSUE THREAD

**Issue by sankichi92** [sankichi92/LiveLog#1256]
https://sentry.io/organizations/livelog/issues/2322637120/?referrer=github_plugin

```
Auth0::NotFound: {"statusCode":404,"error":"Not Found","message":"The user does not exist.","errorCode":"inexistent_user"}
  app/models/auth0_user.rb:17:in `fetch!'
    response = AppAuth0Client.instance.user(auth0_id, fields: fields.join(','))
  app/models/user.rb:43:in `fetch_auth0_user!'
    Auth0User.fetch!(auth0_id)
  app/models/user.rb:52:in `invite!'
    fetch_auth0_user!
  app/controllers/admin/members_controller.rb:31:in `create'
    @member.user.invite!
...
(88 additional frame(s) were not displayed)

Auth0::BadRequest: {"statusCode":400,"error":"Bad Request","message":"The connection does not exist.","errorCode":"inexistent_connection"}
  app/models/auth0_user.rb:22:in `create!'
    response = AppAuth0Client.instance.create_user(
  app/models/user.rb:54:in `rescue in invite!'
    Auth0User.create!(self)
  app/models/user.rb:51:in `invite!'
    @auth0_user = begin
  app/controllers/admin/members_controller.rb:31:in `create'
    @member.user.invite!
...
(88 additional frame(s) were not displayed)
```

**Comment by sankichi92** [comment]
これだ: https://github.com/auth0/ruby-auth0/blob/master/CHANGELOG.md#api2-users-create_user-method
https://github.com/sankichi92/LiveLog/pull/1059#issuecomment-715294497 でメジャーバージョンアップをノールックでマージしてた……。
Auth0 クライアントはテストで stub してるので CI は通るのは当然……。
