### ISSUE TITLE
NameError: uninitialized constant TweetJob::TwitterClient

### ISSUE THREAD

**Issue by sankichi92** [sankichi92/LiveLog#286]
https://sentry.io/livelog/LiveLog/issues/541469700/

```
NameError: uninitialized constant TweetJob::TwitterClient
Did you mean?  Twitter
  app/jobs/tweet_job.rb:5:in `perform'
    TwitterClient.instance.update(tweet)
  app/models/live.rb:35:in `publish'
    TweetJob.perform_now("#{title} のセットリストが公開されました！\n#{url}")
  app/controllers/lives_controller.rb:60:in `publish'
    @live.publish(live_url(@live))
...
(129 additional frame(s) were not displayed)

NameError: uninitialized constant TweetJob::TwitterClient
Did you mean?  Twitter
```

**Comment by sankichi92** [comment]
http://guides.rubyonrails.org/upgrading_ruby_on_rails.html#autoloading-is-disabled-after-booting-in-the-production-environment
