### ISSUE TITLE
RSpec fails on master branch

### ISSUE THREAD

**Issue by sankichi92** [sankichi92/LiveLog#446]
いつからか spec がコケるようになっていた。

```
expected #<Song id: nil, name: "Hourglass", artist: "Aerosmith", youtube_id: "https://www.youtube.com/watch?v=2TL90rxt9bo", live_id: nil, order: 12, time: nil, created_at: nil, updated_at: nil, status: "closed", comment: "液体 こはん 陳列室。　おりめ 雇用 ふくへい。　魔術 あくれい おきゃくさん。", original: false> to be valid, but got errors: ライブを入力してください

  0) Song should be valid
     Failure/Error: it { is_expected.to be_valid }
       expected #<Song id: nil, name: "Hourglass", artist: "Aerosmith", youtube_id: "https://www.youtube.com/watch?v=2TL90rxt9bo", live_id: nil, order: 12, time: nil, created_at: nil, updated_at: nil, status: "closed", comment: "液体 こはん 陳列室。　おりめ 雇用 ふくへい。　魔術 あくれい おきゃくさん。", original: false> to be valid, but got errors: ライブを入力してください
     # ./spec/models/song_spec.rb:20:in `block (2 levels) in <top (required)>'


expected: "-gKPuxV3MkY"
     got: "https://www.youtube.com/watch?v=-gKPuxV3MkY"

(compared using ==)


  0) Song#save with valid youtube url should extract the id from the url
     Failure/Error: expect(song.youtube_id).to eq '-gKPuxV3MkY'
     
       expected: "-gKPuxV3MkY"
            got: "https://www.youtube.com/watch?v=-gKPuxV3MkY"
     
       (compared using ==)
     # ./spec/models/song_spec.rb:66:in `block (5 levels) in <top (required)>'
     # ./spec/models/song_spec.rb:64:in `each'
     # ./spec/models/song_spec.rb:64:in `block (4 levels) in <top (required)>'

```

**Comment by sankichi92** [comment]
```
$ git bisect start 0ba8f213df9d78ede9ce213bc87746dd5f584048 83d08af1ca66e1f4e3d141e02612adfe67a9fc97
Bisecting: 8 revisions left to test after this (roughly 3 steps)
[1cc28d4f2bcaedaed68985e8576ab307473f681b] Bump action_args from 2.3.2 to 2.4.0 (#434)

$ git bisect run 'bundle exec rspec spec/models/song_spec.rb'
running bundle exec rspec spec/models/song_spec.rb
/usr/local/Cellar/git/2.20.1/libexec/git-core/git-bisect: line 459: bundle exec rspec spec/models/song_spec.rb: No such file or directory
Bisecting: 3 revisions left to test after this (roughly 2 steps)
[b94fd9b287d0036ed575a661c927c0802ac0c3c5] Bump bootstrap from 4.2.1 to 4.3.0 (#429)
running bundle exec rspec spec/models/song_spec.rb
/usr/local/Cellar/git/2.20.1/libexec/git-core/git-bisect: line 459: bundle exec rspec spec/models/song_spec.rb: No such file or directory
Bisecting: 1 revision left to test after this (roughly 1 step)
[dfa2b7db1690602aeb14cc21a1d307549de40a7c] Bump bootsnap from 1.3.2 to 1.4.0 (#428)
running bundle exec rspec spec/models/song_spec.rb
/usr/local/Cellar/git/2.20.1/libexec/git-core/git-bisect: line 459: bundle exec rspec spec/models/song_spec.rb: No such file or directory
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[9abf2232aacb99e99d013448be2c762839c721f4] Bump factory_bot_rails from 4.11.1 to 5.0.0 (#426)
running bundle exec rspec spec/models/song_spec.rb
/usr/local/Cellar/git/2.20.1/libexec/git-core/git-bisect: line 459: bundle exec rspec spec/models/song_spec.rb: No such file or directory
9abf2232aacb99e99d013448be2c762839c721f4 is the first bad commit
commit 9abf2232aacb99e99d013448be2c762839c721f4
Author: dependabot[bot] <dependabot[bot]@users.noreply.github.com>
Date:   Mon Feb 4 20:26:48 2019 +0000

    Bump factory_bot_rails from 4.11.1 to 5.0.0 (#426)

:100644 100644 758a6221f6380166299a7956306ff2ecb62c07fe 73a7adc314a3b5796c39e87caafce4c3bcdf58b5 M      Gemfile
:100644 100644 f354464b089fdb84c1a8ebb375fe5021dd309aa7 09160894431b214884f2e72e336b67bbab7aa239 M      Gemfile.lock
bisect run success
```

factory_bot_rails のメジャーバージョン上がったのが原因か……。

**Comment by sankichi92** [comment]
https://www.rubydoc.info/gems/factory_bot/file/GETTING_STARTED.md#Associations

> In factory_bot 5, associations default to using the same build strategy as their parent object:

この辺っぽいなあ
