### ISSUE TITLE
MiniMagick::Error: `mogrify -auto-orient /tmp/ActiveStorage-2260-20191031-4-1677mvv.CR2` failed with error:

### ISSUE THREAD

**Issue by sankichi92** [sankichi92/LiveLog#628]
https://sentry.io/organizations/livelog/issues/1302416226/?referrer=github_plugin

```
MiniMagick::Error: `mogrify -auto-orient /tmp/ActiveStorage-2260-20191031-4-1677mvv.CR2` failed with error:
mogrify-im6.q16: delegate failed `'ufraw-batch' --silent --create-id=also --out-type=png --out-depth=16 '--output=%u.png' '%i'' @ error/delegate.c/InvokeDelegate/1919.
mogrify-im6.q16: unable to open image `/tmp/magick-1470Vi0sC1RYyiTv.ppm': No such file or directory @ error/blob.c/OpenBlob/2701.

  mini_magick/shell.rb:17:in `run'
    fail MiniMagick::Error, "`#{command.join(" ")}` failed with error:\n#{stderr}"
  mini_magick/tool.rb:90:in `call'
    stdout, stderr, status = shell.run(command, options)
  mini_magick/tool.rb:38:in `new'
    instance.call
  mini_magick/image.rb:573:in `mogrify'
    MiniMagick::Tool::MogrifyRestricted.new do |builder|
  active_storage/transformers/mini_magick_transformer.rb:13:in `block in process'
    image.mogrify do |command|
...
(123 additional frame(s) were not displayed)
```

**Comment by sankichi92** [comment]
プロフィール画像に `.CR2` 上げた人がいるな……。

**Comment by sankichi92** [comment]
取り急ぎプロフィール画像削除して対応。

```ruby
user = User.find(734)
user.avatar.purge
user.touch
```
