### ISSUE TITLE
"ライブ名はすでに存在します" で CI がコケる

### ISSUE THREAD

**Issue by sankichi92** [sankichi92/LiveLog#769]
https://travis-ci.com/sankichi92/LiveLog/jobs/277197464

```
Failures:
  1) admin/songs request: GET /admin/entries with playable_time responds 200
     Failure/Error: create_list(:entry, 3)
     
     ActiveRecord::RecordInvalid:
       バリデーションに失敗しました: ライブ名はすでに存在します
     # ./spec/requests/admin/entries_request_spec.rb:12:in `block (3 levels) in <main>'
```

**Comment by sankichi92** [comment]
https://travis-ci.com/sankichi92/LiveLog/builds/145095027

```
Failures:
  1) entries request: GET /entries when logged-in user has entries responds 200
     Failure/Error: song = create(:song, :unpublished, members: [user.member])
     
     ActiveRecord::RecordInvalid:
       バリデーションに失敗しました: ライブ名はすでに存在します
     # ./spec/requests/entries_request_spec.rb:16:in `block (5 levels) in <main>'
     # ./spec/requests/entries_request_spec.rb:15:in `times'
     # ./spec/requests/entries_request_spec.rb:15:in `block (4 levels) in <main>'
```

**Comment by sankichi92** [comment]
https://travis-ci.com/sankichi92/LiveLog/builds/145095009

```
Failures:
  1) entries request: GET /entries when logged-in user has entries responds 200
     Failure/Error: song = create(:song, :unpublished, members: [user.member])
     
     ActiveRecord::RecordInvalid:
       バリデーションに失敗しました: ライブ名はすでに存在します
     # ./spec/requests/entries_request_spec.rb:16:in `block (5 levels) in <main>'
     # ./spec/requests/entries_request_spec.rb:15:in `times'
     # ./spec/requests/entries_request_spec.rb:15:in `block (4 levels) in <main>'
```

**Comment by sankichi92** [comment]
https://travis-ci.com/sankichi92/LiveLog/builds/145911755
