### ISSUE TITLE
Remove `coffee-rails`

### ISSUE THREAD

**Issue by sankichi92** [sankichi92/LiveLog#89]
Just removing `coffee-rails` from Gemfile will cause build failures on Heroku.

```
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       Yarn executable was not detected in the system.
       Download Yarn at https://yarnpkg.com/en/docs/install
       rake aborted!
       LoadError: cannot load such file -- coffee_script
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `block in require'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:258:in `load_dependency'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/autoload/coffee_script.rb:1:in `<top (required)>'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `block in require'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:258:in `load_dependency'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/coffee_script_processor.rb:15:in `cache_key'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:93:in `processor_cache_key'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:22:in `block in initialize'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:53:in `processor_cache_key'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:102:in `block in processors_cache_keys'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:102:in `map'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:102:in `processors_cache_keys'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processing.rb:159:in `resolve_processors_cache_key_uri'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets.rb:162:in `block in <module:Sprockets>'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/dependencies.rb:67:in `resolve_dependency'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:23:in `block in initialize'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:59:in `resolve_dependency'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:268:in `block in resolve_dependencies'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:268:in `map'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:268:in `resolve_dependencies'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:55:in `block in load'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:311:in `block in fetch_asset_from_dependency_cache'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:307:in `each'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:307:in `each_with_index'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:307:in `fetch_asset_from_dependency_cache'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:66:in `find_asset'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:73:in `find_all_linked_assets'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:142:in `block in find'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `each'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `stat_directory'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:227:in `stat_tree'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `each'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `block in logical_paths'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `each'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `logical_paths'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:140:in `find'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:185:in `compile'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/rake/sprocketstask.rb:147:in `with_logger'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
       /tmp/build_3fd2476f946045315a5a7cdafd088f11/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
       Tasks: TOP => assets:precompile
       (See full trace by running task with --trace)
 !
 !     Precompiling assets failed.
```

Running `bin/rails tmp:cache:clear` solved this problem on my local environment.
(cf. https://github.com/rails/sprockets/issues/183#issuecomment-161337599)
However, I did't know how to do this on Heroku.

**Comment by sankichi92** [comment]
6d8e3f917c265bda4180e7044c2a08a4ddabb738
